//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoWPF.View.TextFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextFile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextFile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DemoWPF.View.TextFiles.TextFile", typeof(TextFile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SheetMetalArranger - Demo.
        /// </summary>
        public static string mainWindowTitle {
            get {
                return ResourceManager.GetString("mainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string menuAbout {
            get {
                return ResourceManager.GetString("menuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string menuClose {
            get {
                return ResourceManager.GetString("menuClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to visit mkajzer.pl.
        /// </summary>
        public static string menuWWW {
            get {
                return ResourceManager.GetString("menuWWW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your setup is now being arranged....
        /// </summary>
        public static string progressWindowMessage {
            get {
                return ResourceManager.GetString("progressWindowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed items: .
        /// </summary>
        public static string progressWindowProcessedItems {
            get {
                return ResourceManager.GetString("progressWindowProcessedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See results.
        /// </summary>
        public static string progressWindowSeeResults {
            get {
                return ResourceManager.GetString("progressWindowSeeResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arranging....
        /// </summary>
        public static string progressWindowTitle {
            get {
                return ResourceManager.GetString("progressWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items in set: .
        /// </summary>
        public static string progressWindowTotalItems {
            get {
                return ResourceManager.GetString("progressWindowTotalItems", resourceCulture);
            }
        }
    }
}
