//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoWPF.View.UserControls {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResultsControlTextFile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResultsControlTextFile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DemoWPF.View.UserControls.ResultsControlTextFile", typeof(ResultsControlTextFile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best panel: .
        /// </summary>
        public static string resultsBestPanel {
            get {
                return ResourceManager.GetString("resultsBestPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to calculated.
        /// </summary>
        public static string resultsCalculated {
            get {
                return ResourceManager.GetString("resultsCalculated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrangement results.
        /// </summary>
        public static string resultsHeader {
            get {
                return ResourceManager.GetString("resultsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items arranged: .
        /// </summary>
        public static string resultsItemsArranged {
            get {
                return ResourceManager.GetString("resultsItemsArranged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items left: .
        /// </summary>
        public static string resultsItemsLeft {
            get {
                return ResourceManager.GetString("resultsItemsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not calculated.
        /// </summary>
        public static string resultsNotCalculated {
            get {
                return ResourceManager.GetString("resultsNotCalculated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel no. .
        /// </summary>
        public static string resultsPanelCount {
            get {
                return ResourceManager.GetString("resultsPanelCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to square units.
        /// </summary>
        public static string resultsSquareUnits {
            get {
                return ResourceManager.GetString("resultsSquareUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: .
        /// </summary>
        public static string resultsStatus {
            get {
                return ResourceManager.GetString("resultsStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string resultsSummary {
            get {
                return ResourceManager.GetString("resultsSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total items area: .
        /// </summary>
        public static string resultsTotalItemsArea {
            get {
                return ResourceManager.GetString("resultsTotalItemsArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total panel area: .
        /// </summary>
        public static string resultsTotalPanelArea {
            get {
                return ResourceManager.GetString("resultsTotalPanelArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall utilisation: .
        /// </summary>
        public static string resultsUtilisation {
            get {
                return ResourceManager.GetString("resultsUtilisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worst panel: .
        /// </summary>
        public static string resultsWorstPanel {
            get {
                return ResourceManager.GetString("resultsWorstPanel", resourceCulture);
            }
        }
    }
}
